services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_NAME} 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
