services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_NAME} 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  cura:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3000:3000
    depends_on:
      - db
