services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}  
      POSTGRES_DB: ${DB_NAME} 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
  cura:
    build: .
    environment:
      DB_USER: ${DB_USER} 
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_HOST: ${DB_HOST} 
      DB_NAME: ${DB_NAME} 
      DB_PORT: ${DB_PORT} 
    ports:
      - 3000:3000
    depends_on:
      - db
